version: '3.1'
# add volumes for pgdata?
services:
  db:
    image: postgres:14
    restart: always
    container_name: db
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
  pgadmin:
    image: dpage/pgadmin4:6.12
    container_name: pgadmin
    ports:
      - 5050:80
    environment:
      PGADMIN_DEFAULT_EMAIL: user@email.com
      PGADMIN_DEFAULT_PASSWORD: password
    volumes:
      - ./servers.json:/pgadmin4/servers.json
